### ISSUE TITLE
How can I output it as a stream ?

### ISSUE THREAD

**Issue by Avencheng** [futzu/SuperKabuki#4]
I have a stream as input, and also want to output it as a stream over UDP, but I got the error `FileNotFoundError: [Errno 2] No such file or directory: 'udp://127.0.0.1:10002`
How can I fix this? Thanks a lot!
```
stream = 'udp://127.0.0.1:10000'
sidecar_file = 'sidecar.txt'
sream_w_SCTE35 = 'udp://127.0.0.1:10002'

insert_35_cmd = [
'superkabuki',
'-i', stream,
'-o', sream_w_SCTE35,
'-s', sidecar_file,
'-p', '0x86'
]
subprocess.Popen(insert_35_cmd)
```

**Comment by futzu** [comment]
It doesn't write UDP, just files.
take a look at [gums](https://github.com/futzu/gums) 

```js
superkabuki -i input.ts -s sidecar.txt -p 0x86 | gums -a udp://127.0.0.1:1234

        Unicast Stream
        udp://127.0.0.1:1234

        Source
        0.0.0.0:46783

        139.09 MB sent in  0.45 seconds. 307.23 MB/Sec

```

**Comment by Avencheng** [comment]
Thanks for the reply, I really appreciate it. However, I got some error from the command below and can't figure out what is the problem. Could you please help me take a look?
```
(computer_vision) aven.cheng@tgcusers-MacBook-Pro insert_35 % superkabuki -i udp://@235.35.3.5:3537 -s sidecar.txt -p 0x86 | gums -a 235.35.3.5:3538

	Multicast Stream
	udp://@235.35.3.5:3538

	Source
	0.0.0.0:59941

Writing <_io.BufferedWriter name='<stdout>'>
Traceback (most recent call last):
  File "/Users/aven.cheng/anaconda3/envs/computer_vision/bin/superkabuki", line 7, in <module>
    sk.encode()
  File "/Users/aven.cheng/anaconda3/envs/computer_vision/lib/python3.8/site-packages/superkabuki.py", line 191, in encode
    for pkt in self._find_start():
TypeError: 'bool' object is not iterable 
```
the content of the sidecar.txt
```
(computer_vision) aven.cheng@tgcusers-MacBook-Pro insert_35 % cat sidecar.txt
19.9767,/DAvAAAAAAAA///wFAVIAACPf+/+ABtvDn4AUsz1AAAAAAAKAAhDVUVJAAABNdgHxgg=
276.01,/DAvAAAAAAAA///wFAVIAACPf+/+AXsKxn4AUsz1AAAAAAAKAAhDVUVJAAABNd4UAp4=
```

I also tried the command below which worked find for me before, but now it shows the same error as above.
```
(computer_vision) aven.cheng@tgcusers-MacBook-Pro insert_35 % superkabuki -i independent_frame.ts -o output.ts -s sidecar.txt -p 0x86
Writing output.ts
Traceback (most recent call last):
  File "/Users/aven.cheng/anaconda3/envs/computer_vision/bin/superkabuki", line 7, in <module>
    sk.encode()
  File "/Users/aven.cheng/anaconda3/envs/computer_vision/lib/python3.8/site-packages/superkabuki.py", line 191, in encode
    for pkt in self._find_start():
TypeError: 'bool' object is not iterable
```
Let me know If you need more information, thanks
